version: '3.8'
services:
  frontend:
    image: docker.io/your-dockerhub/enterprise-frontend:latest
    restart: unless-stopped
    expose:
      - "80"

  backend:
    image: docker.io/your-dockerhub/enterprise-backend:latest
    restart: unless-stopped
    environment:
      - PORT=3001
    expose:
      - "3001"

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf:/etc/letsencrypt
    depends_on:
      - frontend
      - backend

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf:/etc/letsencrypt
    entrypoint: /bin/sh -c
    command: "while :; do sleep 12h & wait $${!}; certbot renew --webroot -w /var/www/certbot --quiet; done"
